# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  stock-app:
    image: stock:latest
    build:
      context: ""
      dockerfile: Dockerfile
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stock-postgresql:5432/stock
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://stock-postgresql:5432/stock
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8090:8090
    depends_on:
      - stock-postgresql
  stock-postgresql:
    image: postgres:14.2
    # volumes:
    #   - ~/volumes/user/stock/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=stock
      - POSTGRES_PASSWORD= stock
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
